api_version = "2025-01"

[[extensions]]
uid = "2b801f24-4eb1-8eb5-8aca-0236e754f0e362063d57"
type = "theme"
name = "Pure Wishlist"
handle = "wishlist-theme"

  [[extensions.assets]]
  path = "assets/wishlist.js"

  [[extensions.assets]]
  path = "assets/wishlist.css"
