name = "Pure Wishlist"
client_id = "de38910e605ae6e1a2c3c753faea0b92"  # COLOQUE SEU API KEY COMPLETO AQUI
application_url = "https://purewishlist.vercel.app"  # SUBSTITUA PELA SUA URL REAL
embedded = true

[access_scopes]
scopes = "read_products,read_customers,write_products,read_orders"

[auth]
redirect_urls = [
  "https://purewishlist.vercel.app/auth/callback",
]

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = ["orders/paid"]
  uri = "/webhooks/orders/paid"

  [webhooks.privacy_compliance]
  customer_data_request_url = "/webhooks/customers/data_request"
  customer_deletion_url = "/webhooks/customers/redact"
  shop_deletion_url = "/webhooks/shop/redact"

[app_proxy]
url = "https://purewishlist.vercel.app/api/proxy"
subpath = "wishlist"
prefix = "apps"

[pos]
embedded = false
